export const DATA_DESA: Desa[] = [
  {
    code: "35.14.10.2001",
    name: "JATIARJO",
    petugas: "AHMAD ARROSYID",
    alamat_petugas: "Desa Jatiarjo",
  },
  {
    code: "35.14.10.2002",
    name: "WATUAGUNG",
    petugas: "MOH. ANAS WAHYUDIN",
    alamat_petugas: "Desa Watuagung",
  },
  {
    code: "35.14.10.2003",
    name: "DAYUREJO",
    petugas: "IMRON ROSADI",
    alamat_petugas: "Desa Dayurejo",
  },
  {
    code: "35.14.10.2004",
    name: "BULUKANDANG",
    petugas: "MOHAMAD ROHIMIN",
    alamat_petugas: "Desa Bulukandang",
  },
  {
    code: "35.14.10.2005",
    name: "KETANIRENG",
    petugas: "NUR KHOLIS",
    alamat_petugas: "Desa Ketanireng",
  },
  {
    code: "35.14.10.2006",
    name: "SUKOLELO",
    petugas: "MISBAHUL MUNIR",
    alamat_petugas: "Desa Sukolelo",
  },
  {
    code: "35.14.10.1007",
    name: "LEDUG",
    petugas: "TAUCHID",
    alamat_petugas: "Desa Ledug",
  },
  {
    code: "35.14.10.1008",
    name: "PECALUKAN",
    petugas: "ROIFIN",
    alamat_petugas: "Desa Pecalukan",
  },
  {
    code: "35.14.10.1009",
    name: "PRIGEN",
    petugas: "SUGIONO",
    alamat_petugas: "Desa Prigen",
  },
  {
    code: "35.14.10.2010",
    name: "LUMBANGREJO",
    petugas: "TAMIM",
    alamat_petugas: "Desa Lumbangrejo",
  },
  {
    code: "35.14.10.2011",
    name: "SUKORENO",
    petugas: "AMIN HAUDI",
    alamat_petugas: "Desa Sukoreno",
  },
  {
    code: "35.14.10.2012",
    name: "SEKARJOHO",
    petugas: "ACHMAD NUR CHUSAINI",
    alamat_petugas: "Desa Sekarjoho",
  },
  {
    code: "35.14.10.2013",
    name: "GAMBIRAN",
    petugas: "NONOK NARIYANTO",
    alamat_petugas: "Desa Gambiran",
  },
  {
    code: "35.14.10.2014",
    name: "CANDIWATES",
    petugas: "YAHYA",
    alamat_petugas: "Desa Candiwates",
  },
];
