# fly.toml app configuration file generated for prigen-panwascam-portal on 2023-12-17T00:04:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prigen-panwascam-portal"
primary_region = "sin"

[build]

[env]
  NEXT_PUBLIC_DB_LINK = "https://gist.githubusercontent.com/ifanfairuz/9fad7abb205378c5abb5f4229cabe171/raw/db-panwascam-prigen.json"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
